Xcode project using the rest api
1c3t3a/Covid-19-analysis pull request #110
Opened 2020-12-01 17:41 UTC by cmbTea

Sample does the same as the CSWebClient application

2020-12-01 17:55 UTC, 1c3t3a requested changes
A great implementation! Thank you! I've just found little issues that should be fixed :)

2020-12-01 17:55 UTC, 1c3t3a commented on src/Covid19WebClient/Covid19WebClient/CoronaWebClient.swift
> +  private let _urlPath:String = "/api/data/";
Please insert the missing opening tag.

2020-12-01 17:55 UTC, 1c3t3a commented on src/Covid19WebClient/Covid19WebClient/CoronaWebClient.swift
> +    }
This generates a url of the type `http://mb.cmbt.de/api/data/DE/Cases?&log=True` that's not directly what we want (note the `?&`). It might be better to do it the proper way and let the first option start with `?` and adding all others with `&`.

2020-12-01 17:55 UTC, 1c3t3a commented on src/Covid19WebClient/Covid19WebClient/CoronaWebClient.swift
> +    return (GetChartFromURL(strURL: strURL), strURL)
Concerning my point above, this looks way better!

2020-12-01 17:55 UTC, 1c3t3a commented on src/Covid19WebClient/Covid19WebClient/ViewController.swift
> +  }
Nice code!

2020-12-01 17:58 UTC, 1c3t3a commented
I've also found this file: https://github.com/github/gitignore/blob/master/Global/Xcode.gitignore. Maybe it's good if we extent our gitignore and delete the current files in the working tree.

2020-12-01 18:57 UTC, 1c3t3a requested changes

2020-12-01 18:57 UTC, 1c3t3a commented on src/Covid19WebClient/Covid19WebClient/CoronaWebClient.swift
>      return (GetChartFromURL(strURL: strURL), strURL)
This still doesn't fix the issue. What we want In the end is a URL of the type:
`../api/data/DE/Cases?bar=true&logarithmic`
`../api/data/DE/Cases?bar=true`
`../api/data/DE/Cases`

2020-12-02 12:00 UTC, cmbTea commented on src/Covid19WebClient/Covid19WebClient/CoronaWebClient.swift
> +  private let _urlPath:String = "/api/data/";
Fixed

2020-12-02 12:00 UTC, cmbTea commented on src/Covid19WebClient/Covid19WebClient/CoronaWebClient.swift
>      return (GetChartFromURL(strURL: strURL), strURL)
fixed

2020-12-02 16:08 UTC, merged